apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels: { app: hello }
  template:
    metadata:
      labels: { app: hello }
    spec:
      containers:
      - name: hello
        image: public.ecr.aws/nginx/nginx:latest
        ports: [{ containerPort: 80 }]

---
apiVersion: v1
kind: Service
metadata:
  name: hello-lb
spec:
  selector: { app: hello }
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
